export const sample_food = [
  {
    id: 1,
    name: "Pizza",
    price: 12.99,
    cookTime: "10 min",
    favorite: false,
    origins: "Italy",
    stars: 4.5,
    imageUrl: "perfume.png",
    tag: ["Italian", "Fast food", "Pizza"],
  },
  {
    id: 2,
    name: "Burger",
    price: 9.99,
    cookTime: "5 min",
    favorite: false,
    origins: "USA",
    stars: 4.2,
    imageUrl: "phone.png",
    tag: ["American", "Fast food"],
  },
  {
    id: 3,
    name: "Salad",
    price: 6.99,
    cookTime: "3 min",
    favorite: true,
    origins: "Europe",
    stars: 4.8,
    imageUrl: "playstation.png",
    tag: ["slow food", "Humburger", "Lunch"],
  },
  {
    id: 4,
    name: "Fries",
    price: 4.99,
    cookTime: "2 min",
    favorite: false,
    origins: "USA",
    stars: 4.1,
    imageUrl: "shoes.png",
    tag: ["American", "Fast food", "Lunch"],
  },
  {
    id: 5,
    name: "Pasta",
    price: 10.99,
    cookTime: "15 min",
    favorite: false,
    origins: "Italy",
    stars: 4.7,
    imageUrl: "speakers.png",
    tag: ["Soup", "slow food", "Lunch"],
  },
  {
    id: 6,
    name: "Tacos",
    price: 7.99,
    cookTime: "8 min",
    favorite: false,
    origins: "Mexico",
    stars: 4.6,
    imageUrl: "tv.png",
    tag: ["Fry", "Fast food", "Pizza"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  {
    name: "Fast food",
    count: 4,
  },
  {
    name: "Pizza",
    count: 2,
  },
  {
    name: "Lunch",
    count: 3,
  },
  {
    name: "slow food",
    count: 2,
  },
  {
    name: "Humburger",
    count: 1,
  },
  {
    name: "Fry",
    count: 1,
  },
  {
    name: "Soup",
    count: 1,
  },
];
